# Generated by Django 3.2 on 2022-10-08 02:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('ano', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=4)),
                ('conteudo', models.CharField(max_length=30)),
                ('dificuldade', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Difícil', 'Difícil')], max_length=8)),
                ('link', models.CharField(max_length=1000, verbose_name='Link para o vídeo do youtube, apagar a parte watch?v=, adicionar /embed/o que vem depois do watch?v=, exemplo: https://www.youtube.com/embed/FyOsoRALEG0')),
                ('enunciado1', models.CharField(default='', max_length=1000, verbose_name='Copiar e colar o que tiver escrito no enunciado aqui, este campo é para filtro.')),
                ('enunciado', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Enunciado: Cuidado com o tamanho da imagem, se for colocar')),
                ('alternativa_a', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa A: Cuidado com o tamanho da imagem, se for colocar')),
                ('alternativa_b', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa B: Cuidado com o tamanho da imagem, se for colocar')),
                ('alternativa_c', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa C: Cuidado com o tamanho da imagem, se for colocar')),
                ('alternativa_d', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa D: Cuidado com o tamanho da imagem, se for colocar')),
                ('alternativa_e', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa E: Cuidado com o tamanho da imagem, se for colocar')),
                ('resposta_certa', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], default='', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
