# Generated by Django 3.2 on 2022-10-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoe',
            name='conteudo',
            field=models.CharField(max_length=200),
        ),
    ]
