# Generated by Django 3.2 on 2022-10-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questoe_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoe',
            name='enunciado1',
            field=models.CharField(default='', max_length=4000, verbose_name='Copiar e colar o que tiver escrito no enunciado aqui, este campo é para filtro.'),
        ),
    ]
