# Generated by Django 3.2 on 2023-07-09 01:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_questoe_enunciado1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='questoe',
            name='alternativa_a',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa A: '),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='alternativa_b',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa B: '),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='alternativa_c',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa C: '),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='alternativa_d',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa D: '),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='alternativa_e',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Alternativa E: '),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='ano',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='enunciado',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Enunciado:'),
        ),
        migrations.AlterField(
            model_name='questoe',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='Link para o vídeo do youtube'),
        ),
    ]
