# Generated by Django 5.2.2 on 2025-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230708_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoe',
            name='ano',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=4),
        ),
    ]
