# Generated by Django 5.2.14 on 2026-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_questoe_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoe',
            name='ano',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4),
        ),
    ]
