# Generated by Django 5.2.14 on 2026-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_figura', models.TextField(max_length=100)),
                ('capa', models.ImageField(upload_to='')),
            ],
        ),
    ]
