# Generated by Django 5.2.14 on 2026-06-02 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='capa',
            field=models.ImageField(upload_to='modelagens/capas'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='nome_figura',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ImagemFigura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='modelagens/fotos')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='materiais_apoio.figura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelagemFigura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='modelagens/arquivos/')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='materiais_apoio.figura')),
            ],
        ),
    ]
