# Generated by Django 5.2.14 on 2026-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0002_alter_figura_capa_alter_figura_nome_figura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemfigura',
            name='imagem',
            field=models.ImageField(help_text='Obs: COLOCAR IMAGEM DA CAPA AQUI TAMBÉM', upload_to='modelagens/fotos'),
        ),
    ]
