# Generated by Django 5.2.14 on 2026-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0003_alter_imagemfigura_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='cortadora_laser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='figura',
            name='impressora_3d',
            field=models.BooleanField(default=False),
        ),
    ]
