# Generated by Django 5.2.14 on 2026-06-04 17:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0004_figura_cortadora_laser_figura_impressora_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='descrição'),
            preserve_default=False,
        ),
    ]
