# Generated by Django 5.2.14 on 2026-06-04 17:11

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0005_figura_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogo', models.CharField(max_length=100)),
                ('impressora_3d', models.BooleanField(default=False)),
                ('cortadora_laser', models.BooleanField(default=False)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='descrição')),
                ('capa', models.ImageField(upload_to='modelagens/capas')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Obs: COLOCAR IMAGEM DA CAPA AQUI TAMBÉM', upload_to='modelagens/fotos')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='materiais_apoio.jogo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelagemJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='modelagens/arquivos/')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='materiais_apoio.jogo')),
            ],
        ),
    ]
