# Generated by Django 5.2.14 on 2026-06-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0006_jogo_imagemjogo_modelagemjogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figura',
            name='descricao',
        ),
    ]
