# Generated by Django 5.2.14 on 2026-06-08 17:26

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0007_remove_figura_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestaoModelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.CharField(max_length=10)),
                ('ano', models.CharField(max_length=10)),
                ('impressora_3d', models.BooleanField(default=False)),
                ('cortadora_laser', models.BooleanField(default=False)),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='descrição')),
                ('capa', models.ImageField(upload_to='modelagens/capas')),
            ],
            options={
                'verbose_name': 'Questao Modelada',
                'verbose_name_plural': 'Questoes Modeladas',
            },
        ),
        migrations.CreateModel(
            name='ModelagemQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='modelagens/arquivos/')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='materiais_apoio.questaomodelada')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Obs: COLOCAR IMAGEM DA CAPA AQUI TAMBÉM', upload_to='modelagens/fotos')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='materiais_apoio.questaomodelada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
