# Generated by Django 5.2.14 on 2026-06-08 17:40

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_questoe_ano'),
        ('materiais_apoio', '0008_questaomodelada_modelagemquestao_imagemquestao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questaomodelada',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='questaomodelada',
            name='numero_questao',
        ),
        migrations.AddField(
            model_name='questaomodelada',
            name='questao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='modelagens', to='app.questoe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questaomodelada',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='descrição da modelagem'),
        ),
    ]
