# Generated by Django 5.2.14 on 2026-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0009_remove_questaomodelada_ano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelagemfigura',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='modelagemjogo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='modelagemquestao',
            name='nome',
        ),
    ]
