# Generated by Django 5.2.14 on 2026-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0010_remove_modelagemfigura_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemfigura',
            name='imagem',
            field=models.ImageField(upload_to='modelagens/fotos'),
        ),
        migrations.AlterField(
            model_name='imagemjogo',
            name='imagem',
            field=models.ImageField(upload_to='modelagens/fotos'),
        ),
        migrations.AlterField(
            model_name='imagemquestao',
            name='imagem',
            field=models.ImageField(upload_to='modelagens/fotos'),
        ),
    ]
