# Generated by Django 5.2.14 on 2026-07-06 16:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_apoio', '0011_alter_imagemfigura_imagem_alter_imagemjogo_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='descrição'),
            preserve_default=False,
        ),
    ]
